float widthSquare, heightSquare, border=0.0;
int numPadColumns = 3;
float[] x = new float [numPadColumns];
int numPadRows = 5;
float[] y = new float [numPadRows];
boolean p = false;
float rectX, rectY, rectWidth, rectHeight, size;
color ink;
int alignX, alignY;
String text;
char a;
float title, titleX, titleY, titleWidth, titleHeight;
boolean splash = false;
float backgroundX, backgroundY, backgroundWidth, backgroundHeight;
float PineX, PineY, PineHegiht, PineWidth;
float seaX, seaY, seaWidth, seaHeight;
