float widthSquare, heightSquare, border=0.0;
int numPadColumns = 3;
float[] x = new float [numPadColumns];
int numPadRows = 5;
float[] y = new float [numPadRows];
boolean p = false;
float rectX, rectY, rectWidth, rectHeight, size;
color ink;
int alignX, alignY;
String text;
char a;
int title, titleX, titleY, titleWidth, titleHeight;
